# Generated by Django 5.1.7 on 2025-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(choices=[('Bhojpur', 'Bhojpur'), ('Dhankuta', 'Dhankuta'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Khotang', 'Khotang'), ('Morang', 'Morang'), ('Okhaldhunga', 'Okhaldhunga'), ('Panchthar', 'Panchthar'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Solukhumbu', 'Solukhumbu'), ('Sunsari', 'Sunsari'), ('Taplejung', 'Taplejung'), ('Terhathum', 'Terhathum'), ('Udayapur', 'Udayapur'), ('Bara', 'Bara'), ('Dhanusha', 'Dhanusha'), ('Mahottari', 'Mahottari'), ('Parsa', 'Parsa'), ('Rautahat', 'Rautahat'), ('Saptari', 'Saptari'), ('Sarlahi', 'Sarlahi'), ('Siraha', 'Siraha'), ('Bhaktapur', 'Bhaktapur'), ('Chitwan', 'Chitwan'), ('Dhading', 'Dhading'), ('Dolakha', 'Dolakha'), ('Kathmandu', 'Kathmandu'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Lalitpur', 'Lalitpur'), ('Makwanpur', 'Makwanpur'), ('Nuwakot', 'Nuwakot'), ('Ramechhap', 'Ramechhap'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Sindhupalchok', 'Sindhupalchok'), ('Baglung', 'Baglung'), ('Gorkha', 'Gorkha'), ('Kaski', 'Kaski'), ('Lamjung', 'Lamjung'), ('Manang', 'Manang'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Nawalparasi East', 'Nawalparasi East'), ('Parbat', 'Parbat'), ('Syangja', 'Syangja'), ('Tanahun', 'Tanahun'), ('Arghakhanchi', 'Arghakhanchi'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Dang', 'Dang'), ('Gulmi', 'Gulmi'), ('Kapilvastu', 'Kapilvastu'), ('Nawalparasi West', 'Nawalparasi West'), ('Palpa', 'Palpa'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rupandehi', 'Rupandehi'), ('Rukum East', 'Rukum East'), ('Dailekh', 'Dailekh'), ('Dolpa', 'Dolpa'), ('Humla', 'Humla'), ('Jajarkot', 'Jajarkot'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Mugu', 'Mugu'), ('Rukum West', 'Rukum West'), ('Salyan', 'Salyan'), ('Surkhet', 'Surkhet'), ('Achham', 'Achham'), ('Baitadi', 'Baitadi'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Dadeldhura', 'Dadeldhura'), ('Darchula', 'Darchula'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Community', 'Community'), ('Private', 'Private'), ('Other', 'Other')], max_length=50),
        ),
    ]
