# Generated by Django 5.1.7 on 2025-03-28 16:49

from django.db import migrations

def update_province_name(apps, schema_editor):
    School = apps.get_model('api', 'School')
    # Update all schools with Province No. 1 to Koshi Pradesh
    School.objects.filter(province='Province No. 1').update(province='Koshi Pradesh')

def reverse_province_name(apps, schema_editor):
    School = apps.get_model('api', 'School')
    # Revert Koshi Pradesh back to Province No. 1 if needed
    School.objects.filter(province='Koshi Pradesh').update(province='Province No. 1')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_school_district_alter_school_latitude_and_more'),
    ]

    operations = [
         migrations.RunPython(update_province_name, reverse_province_name),
    ]
