# Generated by Django 5.1.7 on 2025-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_school_google_maps_link_alter_school_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='bio',
            field=models.TextField(blank=True, help_text='School description, history, and other important information', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_images/'),
        ),
    ]
